### PR TITLE
platform support

### LINKED ISSUE #241: docker-builder: Support multiarch (arm64)
The docker image builder currently only supports amd64. It needs to extended to support renovate on `ARM64` renovatebot/renovate#9229

**Features**
- Build multiple arch images and tag them as `{major}.{minor}.{patch}-{arch}`
- Only push images when image id changes, so no docker tag timestamps are changed
- create image list manifests for every version as `{major}.{minor}.{patch}`
- only push if manifests differ
- create short tags of image lists when `major-minor=true`
- only push short tags, if manifests differ

---

This feature needs a community contribution as the renovate maintainers do not need this.

### PR DESCRIPTION
**Pull request by hef**
closes #241

### CODE REVIEW

**Comment by hef** [comment]
relevant too https://github.com/containerbase/buildpack/pull/47#discussion_r631596722_

**Comment by hef** [comment]
This should also help make https://github.com/renovatebot/renovate/issues/9229 solvable.

**Comment by viceice** [comment]
I need some more time to think about it. Currently we only push a new image when the if has changed. For multi platform builds it makes that a lot more complicated. We should publish platform suffixed images first and then a image list manifest containing all platforms. This should only happen if image IDs change. Otherwise the release timestamp of our images will move constantly. We don't like that default docker push behavior that's why we implemented it like it is now.

Maybe we need to accept those changes to have more simplified builds with buildx (bake).

Another this we first need it to update the containerbase binary prebuilds. They need to build the arm binaries before we can build any docker  images for arm.

**Review by viceice — CHANGES_REQUESTED** [review]
see #241 for required implementation features

**Pull request closed without merging**
